# sf: 4

task_type: 'enhancement'

hyper_parameters:
  stage: Stage1
  N_timesteps: 20
  lora_rank_vae: 16
  lora_rank_unet: 32
  prompt_len: 1
  current_task: ${task_type}
  task_list: ['enhancement', 'detection', 'small_targets', 'segmentation']

validation:
  lq_path: /path/to/HM-TIR/test_LQ
  # lq_path: /path/to/detection/images
  # lq_path: /path/to/segmentation/images
  # lq_path: /path/to/small_target/images

  # lq_path: path/to/LQ

  io_backend:
    type: disk