# sf: 4

task_type: 'enhancement'

hyper_parameters:
  stage: Stage1
  N_timesteps: 20
  lora_rank_vae: 16
  lora_rank_unet: 32
  prompt_len: 1
  current_task: ${task_type}
  task_list: ['enhancement', 'detection', 'small_targets', 'segmentation']

validation:
  lq_path: /data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/test_LQ/composited_hard
  # lq_path: /data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/Detection
  # lq_path: /data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/Segmentation
  # lq_path: /data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/SmallTarget_val

  # lq_path: path/to/LQ

  io_backend:
    type: disk