task_type: 'enhancement'  # default task for visualization

task_weights:
  # enhancement: 0.4
  detection: 0.5
  # small_targets: 0.2
  segmentation: 0.5

num_val_visualizations_per_task: 10

# Optional: if omitted for a task, args.pos_prompt will be used.
task_prompts: null
  # enhancement: ''
  # detection: ''
  # segmentation: ''
  # small_targets: ''

hyper_parameters:
  stage: Stage2
  N_timesteps: 20
  lora_rank_vae: 16
  lora_rank_unet: 32
  prompt_len: 1
  current_task: ${task_type}
  task_list: ['detection', 'segmentation']

train:
  enhancement:
    task_type: enhancement
    queue_size: 180
    degradation_synthetic: True

    dataroot_gt: ['/data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/train_GT']
    dataroot_lq: ['/data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/train_GT']

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: True
    use_rot: False

  detection:
    task_type: detection
    queue_size: 180
    degradation_synthetic: True

    dataroot_gt: ['/data/matengyu/data/Infrared/OD/M3FD_yolo/images/train']
    dataroot_lq: ['/data/matengyu/data/Infrared/OD/M3FD_yolo/images/train']
    dataroot_label: ['/data/matengyu/data/Infrared/OD/M3FD_yolo/labels/train'] 

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: True
    use_rot: False

  small_targets:
    task_type: small_targets
    queue_size: 180
    degradation_synthetic: True

    dataroot_gt: ['/data/matengyu/data/Infrared/IRSTD/SIRST3/imgs/train']
    dataroot_lq: ['/data/matengyu/data/Infrared/IRSTD/SIRST3/imgs/train']
    dataroot_label: ['/data/matengyu/data/Infrared/IRSTD/SIRST3/masks_train']

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: True
    use_rot: False

  segmentation:
    task_type: segmentation
    queue_size: 180
    degradation_synthetic: True

    dataroot_gt: ['/data/matengyu/data/Infrared/SS/FMB/train/Infrared']
    dataroot_lq: ['/data/matengyu/data/Infrared/SS/FMB/train/Infrared']
    dataroot_label: ['/data/matengyu/data/Infrared/SS/FMB/train/Label']  

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: True
    use_rot: False


validation:
  enhancement:
    task_type: enhancement
    degradation_synthetic: True

    dataroot_gt: /data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/test_GT
    dataroot_lq: /data/matengyu/data/Infrared/MH-TIR/imgs_Spilt/newdata/test_GT

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: True
    use_rot: False

  detection:
    task_type: detection
    degradation_synthetic: True

    dataroot_gt: '/data/matengyu/data/Infrared/OD/M3FD_yolo/images/val'
    dataroot_lq: '/data/matengyu/data/Infrared/OD/M3FD_yolo/images/val'
    dataroot_label: '/data/matengyu/data/Infrared/OD/M3FD_yolo/labels/val'

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: False
    use_rot: False

  small_targets:
    task_type: small_targets
    degradation_synthetic: True

    dataroot_gt: '/data/matengyu/data/Infrared/IRSTD/SIRST3/imgs/val'
    dataroot_lq: '/data/matengyu/data/Infrared/IRSTD/SIRST3/imgs/val'
    dataroot_label: '/data/matengyu/data/Infrared/IRSTD/SIRST3/masks_val'

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: False
    use_rot: False

  segmentation:
    task_type: segmentation
    degradation_synthetic: True

    dataroot_gt: '/data/matengyu/data/Infrared/SS/FMB/val/Infrared'
    dataroot_lq: '/data/matengyu/data/Infrared/SS/FMB/val/Infrared'
    dataroot_label: '/data/matengyu/data/Infrared/SS/FMB/val/Label'

    crop_size: 512
    io_backend:
      type: disk

    use_hflip: False
    use_rot: False
